
import streamlit as st
import numpy as np
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="Marketing Campaign Analysis",page_icon="📊",layout="wide")
html_title = """<h1 style = "color:white;text-align:center;"> Product Performance </h1>"""
st.markdown(html_title, unsafe_allow_html=True)
df = pd.read_excel('Cleaned Product Performance.xlsx', index_col= 0)
page = st.sidebar.radio('pages',['DataFrame and Overview','Detailed Analysis','Dashboard'])

if page == 'DataFrame and Overview':
    st.header('📊 Marketing Campaign Analysis')
    with st.expander("Data and business understanding"):
        st.write("This dataset provides a comprehensive look at the intersection of marketing expenditure and sales performance for company named ELSA that leveraging multi-channel advertising (Facebook, Google, TikTok, Affiliate) and data-driven promotional campaigns (Flash Sales, Product Bundles) to optimize Customer Acquisition Cost (CAC) and Lifetime Value (LTV).")

    st.dataframe(df)

elif page == 'Detailed Analysis':
    st.header('📊 Exploratory Data Analysis')
    analysis_type = st.tabs(["Univariate","Bivariate","Multivariate"])

    with analysis_type[0]:
        st.subheader("Univariate Analysis")
        st.markdown("Explore the distribution and characteristics of individual variables.")
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            st.metric("Total Records", f"{len(df):,}")
        with col2:
            st.metric(
                "Total Revenue",
                f"{df['Revenue Generated'].sum():,.0f}"
            )
        with col3:
            st.metric(
                "Total Units Sold",
                f"{df['Units Sold'].sum():,.0f}"
            )
        with col4:
            st.metric(
                "Marketing Channels",
                df['Marketing Channels'].nunique()
            )
        with st.expander("💡 What does the data tell us?"):

            st.markdown("""
            ### Univariate Analysis

            Univariate analysis examines one variable at a time.

            It helps us understand:
            - The distribution of the data
            - The overall scale of each variable

            **Business purpose:**  
            Understanding individual variables gives us a foundation
            before investigating relationships between variables.
            """)
        st.divider()
        st.subheader("📈 Variable Distributions")
        targcol = ['Marketing Channels','Subscription_Tier','Revenue Generated', 'Budget', 'Clicks','Conversions', 'ROI', 'Subscription Length','Discount Level','Units Sold','Bundle Price']
        for col in targcol:
            fig = px.histogram(data_frame = df, x = col, text_auto = True,nbins=40).update_xaxes(categoryorder = 'max descending')
            st.plotly_chart(fig, use_container_width = True)
    with analysis_type[1]:
        st.subheader("🔗 Bivariate Analysis")

        st.markdown(
            "Explore relationships and comparisons between two variables."
        )
        with st.expander("💡 What does the data tell us?"):

            st.markdown("""
            ### Bivariate Analysis

            Bivariate analysis investigates the relationship between
            two variables.

            For example:

            **Subscription_Tier → Units Sold**

            This helps us determine which tier with higher units sold.

            **Marketing Channel → ROI**

            This allows us to compare the efficiency of different
            marketing channels.

            **Business purpose:**  
            Identify relationships, differences, and potential patterns
            that can support marketing decisions.
            """)

        st.divider()
        col1, col2 = st.columns(2)

        with col1:

             roi_df = (
                df.groupby("Marketing Channels")["ROI"]
                .mean()
                .sort_values(ascending=False)
                .reset_index())

             fig2 = px.bar(
                roi_df,
                x="Marketing Channels",
                y="ROI",
                title="Average ROI by Marketing Channel",
                text_auto=".2f",height = 500
             ).update_traces(textposition='outside')
             st.plotly_chart(
                        fig2,
                        use_container_width=True
                    )
        with col2:
            plot4_df = df.groupby('Subscription_Tier')['Revenue Generated'].sum().sort_values(ascending=False).reset_index()
            plot4_df['Revenue Generated'] = plot4_df['Revenue Generated'].round().astype(int)
            fig3 = px.bar(data_frame= plot4_df, x='Subscription_Tier', y= 'Revenue Generated',text_auto= True,title = 'Revenue Generated By Tiers',height = 500).update_xaxes(categoryorder = 'max descending').update_traces(textposition='outside')
            st.plotly_chart(
                        fig3,
                        use_container_width=True
                    )
    with analysis_type[2]:
        st.subheader("🎯 Multivariate Analysis")

        st.markdown(
            "Analyze multiple variables together to uncover deeper business insights."
        )

        with st.expander("💡 What does the data tell us?"):

            st.markdown("""
            ### Analysis Description

            This analysis examines three variables simultaneously:

            - **Marketing Channel**
            - **Subscription Tier**
            - **Units Sold**

            The goal is to determine whether the most effective marketing
            channel changes depending on the subscription tier.

            ### Business Insight
             The results can help the company avoid using a
            **one-size-fits-all marketing strategy**.

            If different subscription tiers perform better through
            different channels, marketing resources can be allocated
            according to the behavior of each customer segment.

            ### 💼 Business Application

            This analysis can support:

            - Marketing budget allocation
            - Customer segmentation
            - Campaign targeting
            - Channel optimization
            - Sales strategy
            """)
        st.divider()

        top_channels = (
        df.loc[
            df.groupby("Subscription_Tier")["Clicks"]
            .idxmax()
        ]
        .reset_index(drop=True)
      )
        st.markdown("### 🏆 Best Marketing Channel by Subscription Tier")

        cols = st.columns(len(top_channels))

        for col, (_, row) in zip(cols, top_channels.iterrows()):
             with col:

                st.metric(
                    label=row["Subscription_Tier"],
                    value=row["Marketing Channels"],
                    delta=f"{row['Clicks']:,} Clicks"
                )
        st.divider()
        st.markdown(
        "### 🎯 Marketing Channel × Subscription Tier × Units Sold"
         )
        plot7_df = df.groupby(['Subscription_Tier', 'Marketing Channels'])['Units Sold'].sum().reset_index()
        fig4 = px.bar(
            plot7_df,
            x='Subscription_Tier',
            y='Units Sold',
            color='Marketing Channels',
            barmode='group',
            text_auto=True,
            title='Units Sold by Marketing Channel and Subscription Tier'
           )
        st.plotly_chart(
                        fig4,
                        use_container_width=True
                    )

elif page == 'Dashboard':
    st.caption(
        "A high-level overview of marketing, sales, and campaign performance."
    )
    total_revenue = df["Revenue Generated"].sum()
    revenue_per_unit = df["Revenue Per Unit"].mean()
    revenue_per_click = df["Revenue Per Click"].mean()
    budget_per_conversion = df["Budget per Conversion"].mean()
    total_units = df["Units Sold"].sum()
    total_conversions = df["Conversions"].sum()
    total_clicks = df["Clicks"].sum()
    overall_conversion_rate = (total_conversions / total_clicks * 100)
    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "💰 Total Revenue",
            f"{total_revenue:,.0f}"
        )
    with col2:
        st.metric(
            "📦 Revenue Per Unit",
            f"{revenue_per_unit:,.2f}"
        )

    with col3:
        st.metric(
            "🖱 Revenue Per Click",
            f"{revenue_per_click:,.2f}"
        )
    with col4:
        st.metric(
            "🎯 Budget Per Conversion",
            f"{budget_per_conversion:,.2f}"
        )

    st.divider()
    col1, col2 = st.columns(2)
    with col1:
        month_sorted = df.sort_values('Subscription Length')
        plot2_df = month_sorted.groupby('Subscription Length')['Customer_ID'].count().reset_index()
        fig5 = px.line(data_frame= plot2_df, x= 'Subscription Length', y= 'Customer_ID',
        labels= {'Subscription Length' : 'Month', 'Customer_ID' : 'Customer Count'},
        title= 'Total number of customers per month subscriptions',
        text= 'Customer_ID',
        line_shape= 'spline').update_traces(textposition= 'top center')
        st.plotly_chart(
                        fig5,
                        use_container_width=True
                    )
    with col2:

        units_tier = (
            df.groupby("Subscription_Tier")["Units Sold"]
            .sum()
            .sort_values(ascending=False)
            .reset_index()
        )
        fig6 = px.bar(
            units_tier,
            x="Subscription_Tier",
            y="Units Sold",
            text_auto=True,
            title=" Units Sold by Subscription Tier"
        ).update_layout(
            xaxis_title="Subscription Tier",
            yaxis_title="Units Sold",
            showlegend=False
        )
        st.plotly_chart(
            fig6,
            use_container_width=True
        )
    col1, col2 = st.columns(2)
    with col1:
         roi_channel = (
            df.groupby("Marketing Channels")["ROI"]
            .mean()
            .sort_values(ascending=False)
            .reset_index())
         fig7 = px.bar(
            roi_channel,
            x="Marketing Channels",
            y="ROI",
            text_auto=".2f",
            title="Average ROI by Marketing Channel",height= 520
         ).update_layout(
            xaxis_title="Marketing Channels",
            yaxis_title="Average ROI",
            showlegend=False).update_traces(textposition='outside')
         st.plotly_chart(fig7,use_container_width=True)

    with col2:
        plot3_df = df.groupby('Marketing Channels')['Conversion Rate'].mean().sort_values(ascending=False).reset_index()
        fig8 = px.bar(data_frame= plot3_df, x='Marketing Channels', y= 'Conversion Rate',text_auto= True,title = 'Conversion Rate by Marketing',height= 520).update_xaxes(categoryorder = 'max descending').update_traces(texttemplate='%{y:.2f}%',textposition='outside')
        st.plotly_chart(fig8,use_container_width=True)

    st.divider()

    st.subheader("💡 Key Dashboard Insights")

    revenue_channel = (
        df.groupby("Marketing Channels")["Revenue Generated"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    top_revenue_channel = revenue_channel.iloc[0]["Marketing Channels"]
    top_revenue_value = revenue_channel.iloc[0]["Revenue Generated"]


    units_tier = (
        df.groupby("Subscription_Tier")["Units Sold"]
        .sum()
        .sort_values(ascending=False)
        .reset_index()
    )

    top_units_tier = units_tier.iloc[0]["Subscription_Tier"]
    top_units_value = units_tier.iloc[0]["Units Sold"]


    roi_channel = (
        df.groupby("Marketing Channels")["ROI"]
        .mean()
        .sort_values(ascending=False)
        .reset_index()
    )

    top_roi_channel = roi_channel.iloc[0]["Marketing Channels"]
    top_roi_value = roi_channel.iloc[0]["ROI"]

    conversion_rate_channel = (
        df.groupby("Marketing Channels")
        .agg({
            "Conversions": "sum",
            "Clicks": "sum"
        })
        .reset_index()
    )

    conversion_rate_channel["Conversion Rate"] = (
        conversion_rate_channel["Conversions"]
        / conversion_rate_channel["Clicks"]
        * 100
    )

    conversion_rate_channel = (
        conversion_rate_channel
        .sort_values("Conversion Rate", ascending=False)
    )

    top_conversion_channel = (
        conversion_rate_channel.iloc[0]["Marketing Channels"]
    )

    top_conversion_rate = (
        conversion_rate_channel.iloc[0]["Conversion Rate"]
    )


    budget_revenue_corr = (
        df["Budget"]
        .corr(df["Revenue Generated"])
    )


    col1, col2 = st.columns(2)

    with col1:

        st.info(
            f"""
            ### 📈 ROI Performance

            **{top_roi_channel}** recorded the highest average
            ROI at **{top_roi_value:.2f}**.

            ROI measures the return generated relative to the
            investment associated with the campaign.
            """
        )


    with col2:

        st.info(
            f"""
            ### 🎯 Conversion Performance

            **{top_conversion_channel}** achieved the highest
            overall conversion rate at **{top_conversion_rate:.2f}%**.

            This means this channel converted clicks into
            conversions at the highest rate among the channels.
            """
        )

    st.markdown("### 📊 Overall Performance")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "Total Revenue",
            f"{total_revenue:,.0f}"
        )

    with col2:
        st.metric(
            "Total Units Sold",
            f"{total_units:,.0f}"
        )

    with col3:
        st.metric(
            "Total Conversions",
            f"{total_conversions:,.0f}"
        )

    with col4:
        st.metric(
            "Overall Conversion Rate",
            f"{overall_conversion_rate:.2f}%"
        )


    st.markdown("### 💵 Budget & Revenue Relationship")

    st.write(
        f"""
        The correlation between **Budget** and **Revenue** is
        **{budget_revenue_corr:.2f}**.

        This measures the strength and direction of the linear
        relationship between campaign budget and generated revenue.
        """
    )
